### ISSUE TITLE
generic_ordered_vec 'test_genericity' failling when it shouldn't

### ISSUE THREAD

**Issue by Fymyte** [CohenArthur/rust-gistre-workshop#30]
In file '1_slices_modules_and_objects/exercises/generic_ordered_vec/lib.rs', the test 'test_genericity' doesn't work properly.
There is a pop missing line 125:
```rust
fn test_genericity() {
    let mut ov = OrderedVec::new();
    ov.push(1.5);
    ov.push(0.19);
    ov.push(0.00000005);
    ov.push(67.15);

    assert!(ov.is_sorted());

    assert_eq!(ov.pop(), 0.00000005); // this line
    assert_eq!(ov.pop(), 0.19);
    assert_eq!(ov.pop(), 1.5);
}
```
PS: tried to open a PR to fix this issue but I was unable to push a new branch, failing because of bad access right.

**Comment by CohenArthur** [comment]
In order to create a PR, you need to push the branch on your fork and then ask for a PR against this repo's master. So instead of doing like the exercises and creating a PR against Fymyte/master, you can choose to create one against CohenArthur/master. Thanks for the issue!
